global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "ingestion"
    static_configs:
      - targets: ["ingestion:9100"]

  - job_name: "enrichment"
    static_configs:
      - targets: ["enrichment:9101"]